### ISSUE TITLE
Enhancement: Champion Mastery & MatchList

### ISSUE THREAD

**Issue by Azoy** [amreuland/ashe#1]
Really love this library, but would love it even more if it had these two endpoints. Not too sure if you're working on them or not, but please do. Have a nice day.

**Comment by noriah** [comment]
Really sorry. I've been meaning to add the rest of the endpoints. School is killer
I'm currently getting a lot of service rate limit errors, so I am unable to test it right now. I'll be working on it more later this week.

**Comment by noriah** [comment]
See #2
